name: Root Tests

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  call-frontend-tests:
    uses: ./java/forget-pass/.github/workflows/frontend-tests.yml
    with: {}
  call-backend-tests:
    uses: ./java/forget-pass/.github/workflows/backend-tests.yml
    with: {}
