name: Root Tests

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  call-frontend-tests:
    uses: ./spec-kit_demo/java/forget-pass/.github/workflows/frontend-tests.yml@feature/add-backend-workflow
    with: {}
  call-backend-tests:
    uses: ./spec-kit_demo/java/forget-pass/.github/workflows/backend-tests.yml@feature/add-backend-workflow
    with: {}
